apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {app-name}
  name: {app-name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {app-name}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {app-name}
    spec:
      containers:
      - image: {image-repo}:{image-tag}
        name: {app-name}
        resources: {}
status: {}
