apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {app-name}
  name: {svc-name}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {app-name}
  type: NodePort
status:
  loadBalancer: {}
