# Concouse CI Pipeline definition for Spring Boot

resources:
- name: backline-src
  type: git
  source:
    uri: https://github.com/xlpeabrain/backline
    branch: {{backline-branch}}
- name: backline-docker-image
  type: docker-image
  source:
    repository: xlpeabrain/backline
    username: {{backline-repo-username}}
    password: {{backline-repo-password}}

#- name: java-docker-image
#  type: docker-image
#  source:
#    repository: java
#    tag:        8-jdk


jobs:
- name: build-source
  plan:
  - get: backline-src
#    trigger: true
  - task: build-src
    file: backline-src/ci/build-main.yml
  - put: backline-docker-image
    params:
      build: backline-src
- name: test-image
  plan:
    - get: backline-src
    - get: backline-docker-image
      passed: [build-source]
      trigger: true
    - task: smoke-test-image
      privileged: true
      file: backline-src/ci/test-image.yml
- name: deploy-backline-app
  plan:
    - get: backline-src
    - get: backline-docker-image
#      passed: [build-source]
#      trigger: true
    - task: deploy-app
      file: backline-src/ci/deploy-to-k8s.yml
      privileged: true
      params:
        K8S_API: {{k8s-api}}
        K8S_USER: {{k8s-user}}
        K8S_CLIENT_CERT_DATA: {{k8s-client-cert}}
        K8S_CLIENT_KEY_DATA: {{k8s-client-key}}
        K8S_NAMESPACE: {{k8s-namespace}}
        K8S_TOKEN: {{k8s-token}}
        APP_NAME: {{app-name}}
        IMAGE_REPO: {{image-repo}}
        IMAGE_TAG: {{image-tag}}
        SVC_NAME: {{svc-name}}

