# Concouse CI Pipeline definition for Spring Boot

resources:
- name: backline-src
  type: git
  source:
    uri: https://github.com/xlpeabrain/backline
    branch: {{backline-branch}}
- name: backline-docker-image
  type: docker-image
  source:
    repository: xlpeabrain/backline
    username: {{backline-repo-username}}
    password: {{backline-repo-password}}

#- name: java-docker-image
#  type: docker-image
#  source:
#    repository: java
#    tag:        8-jdk


jobs:
- name: build-source
  plan:
  - get: backline-src
#    trigger: true
  - task: build-src
    file: backline-src/ci/build-main.yml
  - put: backline-docker-image
    params:
      build: backline-src
- name: test-image
  plan:
    - get: backline-src
    - get: backline-docker-image
      passed: [build-source]
      trigger: true
    - task: smoke-test-image
      privileged: true
      file: backline-src/ci/test-image.yml
- name: deploy-backline-app
  plan:
    - get: backline-src
    - get: backline-docker-image
      passed: [build-source]
      trigger: true
    - task: deploy-app
      privileged: true
      file: backline-src/ci/deploy-to-k8s.yml
      params:
        K8S-API: {{k8s-api}}
        K8S-USER: {{k8s-user}}
        K8S-CLIENT-CERT: {{k8s-client-cert}}
        K8S-CLIENT-KEY: {{k8s-client-key}}
        K8S-NAMESPACE: {{k8s-namespace}}

