# Concouse CI Pipeline definition for Spring Boot
resource_types:
- name: gate-resource
  type: docker-image
  source:
    repository: meshcloud/gate-resource

gate-source: &gate-source
  git:
    uri: git@github.com:xlpeabrain/backline.git
    branch: gates
    private_key: {{backline-private-key}}

resources:
- name: backline-src
  type: git
  source:
    uri: https://github.com/xlpeabrain/backline
    branch: {{backline-branch}}
#    paths:
#    - /ci/*
#    - /k8s/*
#    - /src/*
#    - pom.xml
- name: backline-docker-image
  type: docker-image
  source:
    repository: xlpeabrain/backline
    username: {{backline-repo-username}}
    password: {{backline-repo-password}}
- name: success-gate
  type: gate-resource
  source:
    <<: *gate-source
    gate: success


jobs:

- name: build-source
  plan:
  - get: backline-src
    trigger: true
  - task: build-src
    file: backline-src/ci/build-main.yml
  - put: backline-docker-image
    params:
      build: backline-src

- name: test-image
  plan:
    - get: backline-src
    - get: backline-docker-image
      passed: [build-source]
      trigger: true
    - task: smoke-test-image
      privileged: true
      file: backline-src/ci/test-image.yml
    - put: success-gate
      params:
        item_file: gen/*

- name: deploy-to-k8s
  plan:
    - get: success-gate
      passed: [test-image]
      trigger: true
    - get: backline-src
      passed: [test-image]
    - get: backline-docker-image
      passed: [test-image]
    - task: deploy-app
      file: backline-src/ci/deploy-to-k8s.yml
      params:
        K8S_API: {{k8s-api}}
        K8S_USER: {{k8s-user}}
        K8S_NAMESPACE: {{k8s-namespace}}
        K8S_TOKEN: {{k8s-token}}
        APP_NAME: {{app-name}}
        IMAGE_REPO: {{image-repo}}
        IMAGE_TAG: {{image-tag}}
        SVC_NAME: {{svc-name}}

